### ISSUE TITLE
About the consistency loss

### ISSUE THREAD

**Issue by yakexee** [wildphoton/RandConv#2]
Hi, thanks for sharing your code. For the function F.kl_div(), the first parameter is input and the second is target. I am confused why the target is not p_mixture on [L401-L403](https://github.com/wildphoton/RandConv/blob/main/randconv_trainer.py#L401-L403)?
Thanks.

**Comment by wildphoton** [comment]
Hi @yakexee, I think F.kl_div() defines inputs and targets in the way how NLL loss is used. Since NLL(input, target) = cross_entropy(target, input). I believe F.kl_div(input, target) = KL(target || input). You can check this with an easy example by comparing the results with a KL div function implemented by yourself. Since we are computing KL(p_aug || p_mixture), we called F.kl_div(p_mixture, p_aug). FYI, this loss is adapted from the Augmix's [implementation](https://github.com/google-research/augmix/blob/9b9824c7c19bf7e72df2d085d97b99b3bfb00ba4/cifar.py#L232). I hope it helps

**Comment by yakexee** [comment]
Thanks for the kind reply. That helps!
